### ISSUE TITLE
System colour theming option doesn't follow system colours

### ISSUE THREAD

**Issue by Fraaaaaunimib** [CodingWonders/DISMTools#111] opened 2024-04-13 10:43 UTC
**What is the bug about?**
Usually, a "system colour" option in Personalisation should make all the UI elements use the colors inside the System.Colors class. Instead, it uses a very weird mix-match of hardcoded colour values and system colours, like many other modern developed apps.
![immagine](https://github.com/CodingWonders/DISMTools/assets/117264986/e8caddc5-9cd7-4464-a41b-541802000eec)

![immagine](https://github.com/CodingWonders/DISMTools/assets/117264986/3c26669c-773f-448d-98f3-254410cfdcb2)

![immagine](https://github.com/CodingWonders/DISMTools/assets/117264986/3a62fb3b-8343-4858-92f2-bdacc203ed1a)

Upon resizing it of even just a single pixel, it loads the custom dark mode which, although serviceable, it doesn't happen on the first load.
![immagine](https://github.com/CodingWonders/DISMTools/assets/117264986/db066f6d-7874-447d-b373-c0d4ff7623b1)

It seems like though, upon first opening the app, it loads the true system colour mode which... well, doesn't look great. 
![immagine](https://github.com/CodingWonders/DISMTools/assets/117264986/632184a7-bc3f-483a-8455-cdae69de9fdd)

Speaking of which, I shouldn't be able to write anything I'd want in these dropdown boxes.
![immagine](https://github.com/CodingWonders/DISMTools/assets/117264986/36503f75-9999-44ab-b349-d7037ffe106d)

**How does it happen?**
Load any other theme other than aero.msstyles.

**Expected behavior**
On System Color mode, it must theme all the controls using the System.Colors class without any hardcoded colour. While on this mode, it shouldn't switch to dark mode after starting it the first time and then resizing it.

**Comment by CodingWonders** [comment] 2024-04-13 10:46
I see custom controls (a.k.a. buttons). Are you using Rectify11 or a different theme?

**EDIT:** "Use system setting" only detects the color preference of the system and sets the themes automatically

**Comment by Fraaaaaunimib** [comment] 2024-04-13 11:32
In this case yes, but it could happen on any theme that doesn't use the colors of aero.msstyles.

**Comment by CodingWonders** [comment] 2024-04-13 11:35
> In this case yes, but it could happen on any theme that doesn't use the colors of aero.msstyles.

I improved the consistency of dialogs just because of Rectify11, back in the development of version 0.2 (circa December 2022), and haven't considered that since. I'll make a Windows 11 VM and apply Rectify11 to see what happens

**Comment by CodingWonders** [comment] 2024-04-13 11:46
**UPDATE:** installing Windows...

Anyway, as a workaround, try setting up the light theme

**Comment by CodingWonders** [comment] 2024-04-13 13:38
You'll need to provide more information about the components installed with Rectify11 since I can't seem to reproduce it. In some cases, some controls look even more beautiful than on the standard theme to me:

![Rectify11-2024-04-13-15-33-42](https://github.com/CodingWonders/DISMTools/assets/101426328/2a1c32fb-c63d-407e-b004-e5ff52be4155)
![Rectify11-2024-04-13-15-33-58](https://github.com/CodingWonders/DISMTools/assets/101426328/b7a64b2a-530f-4779-a597-a06b3dd03404)
![Rectify11-2024-04-13-15-34-29](https://github.com/CodingWonders/DISMTools/assets/101426328/97bfd071-b7b3-45bc-ac59-29f9d188694f)
![Rectify11-2024-04-13-15-34-39](https://github.com/CodingWonders/DISMTools/assets/101426328/f8864757-b75a-4db8-82f2-1efe243091ff)
![Rectify11-2024-04-13-15-34-51](https://github.com/CodingWonders/DISMTools/assets/101426328/2b770ae2-9865-457e-bfd6-5c9c5281c84d)

**Comment by Fraaaaaunimib** [comment] 2024-04-13 16:07
I've tried redownloading the 0.5 preview version, and I'm having the same problem.
![immagine](https://github.com/CodingWonders/DISMTools/assets/117264986/c8d560e4-8988-4443-9bd7-3448d664d598)

I'm not running the full version of Rectify11, but rather only the theme and certain system files (shouldn't be a problem though), and I'm running the 0.5 preview version from this repo. Just redownloaded it brand new after deleting it too.

I'm also getting these errors upon bootup of the application:
`System.IO.FileNotFoundException: c:\$RECYCLE.BIN\S-1-5-21-3861414630-43215771-1940960715-1001\$RYA0DSI\Windows\system32\ntoskrnl.exe
   in System.Diagnostics.FileVersionInfo.GetVersionInfo(String fileName)
   in DISMTools.MainForm.DetectMountedImages(Boolean DebugLog)
   in DISMTools.MainForm.MainForm_Load(Object sender, EventArgs e)
   in System.EventHandler.Invoke(Object sender, EventArgs e)
   in System.Windows.Forms.Form.OnLoad(EventArgs e)
   in System.Windows.Forms.Form.OnCreateControl()
   in System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   in System.Windows.Forms.Control.CreateControl()
   in System.Windows.Forms.Control.WmShowWindow(Message& m)
   in System.Windows.Forms.Control.WndProc(Message& m)
   in System.Windows.Forms.Form.WmShowWindow(Message& m)
   in System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Error Message: c:\$RECYCLE.BIN\S-1-5-21-3861414630-43215771-1940960715-1001\$RYA0DSI\Windows\system32\ntoskrnl.exe

Error Code (HRESULT): -2147024894

Machine information:
 - Computer manufacturer: Microsoft Corporation
 - Computer model: Surface Laptop 3
 - BIOS name/description: 19.100.140 19.100.140
 - System Management BIOS (SMBIOS) version: 19.100.140

Operating system information:
 - OS name: Microsoft Windows 11 Home
 - OS version: 10.0.22621.0
 - OS Platform: Win32NT
 - Is a 64-bit system? Yes

Processor information:
 - Processor name: Intel(R) Core(TM) i5-1035G7 CPU @ 1.20GHz
 - Processor caption: Intel64 Family 6 Model 126 Stepping 5
 - Processor manufacturer: GenuineIntel
 - Processor family (WMI type): 205
   NOTE: refer to the following website to get the exact family type of your processor:
   https://learn.microsoft.com/en-us/windows/win32/cimwin32prov/win32-processor

This information is gathered to help isolate the issue to a specific hardware or software configuration. No information that can be used to identify the user or the exact system is gathered.

If you don't want to send this information to the developers, paste the text that was copied to the clipboard in a text editor, remove this information, and copy the new text again.

This information has been copied to the clipboard.`

And upon opening Settings, I get this:
`System.ArgumentOutOfRangeException: InvalidArgument=Valore di '1' non valido per 'SelectedIndex'.
Nome parametro: SelectedIndex
   in System.Windows.Forms.ComboBox.set_SelectedIndex(Int32 value)
   in DISMTools.Options.GatherCustomSettings()
   in DISMTools.Options.Options_Load(Object sender, EventArgs e)
   in System.Windows.Forms.Form.OnLoad(EventArgs e)
   in System.Windows.Forms.Form.OnCreateControl()
   in System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   in System.Windows.Forms.Control.CreateControl()
   in System.Windows.Forms.Control.WmShowWindow(Message& m)
   in System.Windows.Forms.Control.WndProc(Message& m)
   in System.Windows.Forms.Form.WmShowWindow(Message& m)
   in System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Error Message: InvalidArgument=Valore di '1' non valido per 'SelectedIndex'.
Nome parametro: SelectedIndex

Error Code (HRESULT): -2146233086

Machine information:
 - Computer manufacturer: Microsoft Corporation
 - Computer model: Surface Laptop 3
 - BIOS name/description: 19.100.140 19.100.140
 - System Management BIOS (SMBIOS) version: 19.100.140

Operating system information:
 - OS name: Microsoft Windows 11 Home
 - OS version: 10.0.22621.0
 - OS Platform: Win32NT
 - Is a 64-bit system? Yes

Processor information:
 - Processor name: Intel(R) Core(TM) i5-1035G7 CPU @ 1.20GHz
 - Processor caption: Intel64 Family 6 Model 126 Stepping 5
 - Processor manufacturer: GenuineIntel
 - Processor family (WMI type): 205
   NOTE: refer to the following website to get the exact family type of your processor:
   https://learn.microsoft.com/en-us/windows/win32/cimwin32prov/win32-processor

This information is gathered to help isolate the issue to a specific hardware or software configuration. No information that can be used to identify the user or the exact system is gathered.

If you don't want to send this information to the developers, paste the text that was copied to the clipboard in a text editor, remove this information, and copy the new text again.

This information has been copied to the clipboard.`

**Comment by CodingWonders** [comment] 2024-04-13 16:14
When testing the program to see if it had this issue, I only applied the theme, so I'm curious to know about the system files that you've installed.

As per the recycle bin exception, I'm stunned that it's pointing there. Maybe you have an image in there?

**Comment by Fraaaaaunimib** [comment] 2024-04-13 16:37
Theoretically no... I did remove the old copy of the program I did download this morning, re-downloaded it, extracted the zip and it's sitting in my Downloads folder. The only thing I can think of being in the recycle bin is the original zip folder, but that shouldn't be a problem... that problem occurs also when I just open the app, before selecting any option.

As far as system files go, I have duires.dll, explorerframe.dll.mun, shell32.dll, and black.msstyles - I don't have the full package installed. They're all from the r11 repo under Files.

I know the developer of r11, I'll ask him too about this so we can know further if it's a problem of the theme 👍

Edit: as I said before though, upon resizing the window, it removed that strange mixmatch theme

**Comment by CodingWonders** [comment] 2024-04-13 17:31
I applied black.msstyles and it still shows up correctly. Needless to say, I have only applied the themes, so something could be up with duires.dll or explorerframe.dll.mun. I ruled out shell32.dll since it only affects system icons for the most part.

![Rectify11-2024-04-13-19-24-22](https://github.com/CodingWonders/DISMTools/assets/101426328/2ff128ee-4b79-46f5-854c-2095dc974909)

I'll do additional testing but, if you want, ask him about this issue. If it affects him as well, it may be a problem with the theme or the DLLs I have mentioned.

**Comment by Fraaaaaunimib** [comment] 2024-04-13 17:47
Upon resizing, it gets fixed and it shows just like your screenshot does. Weird behaviour... I've asked now if he could look into it, I'll update once I get any reply.

![immagine](https://github.com/CodingWonders/DISMTools/assets/117264986/f026d13f-de01-43aa-968f-556f9ca93627)

**Comment by CodingWonders** [comment] 2024-04-13 17:51
By the way, resizing the window is not a weird behavior. It's by design, as it's the functionality of "Hey, let's change the theme automatically when the system changes the theme!"

<p align="center">
  <img src="https://user-images.githubusercontent.com/101426328/235305027-106b284b-f2ae-40d3-9c07-465df6633d96.gif" />
</p>

**Comment by CodingWonders** [comment] 2024-04-14 14:56
@Fraaaaaunimib, any response from the Rectify11 developer?

**Comment by CodingWonders** [comment] 2024-04-14 15:28
A thing I've found out is that there's a registry key that changes when you change the system theme:

![regedit_npjHmATHLz](https://github.com/CodingWonders/DISMTools/assets/101426328/ee45d871-037a-45e4-9e1e-c62bfefd08f6)

Can you show me your `DllName` value stored in `HKCU\Software\Microsoft\Windows\CurrentVersion\ThemeManager`? If it is different from `Aero.msstyles`, then we can check the currently applied theme programmatically

**Comment by Fraaaaaunimib** [comment] 2024-04-14 20:29
winex (the developer) wrote
"Just checked this now because github stopped loading on iOS 15. idk how is that even possible, A/B testing???"

That's why I didn't write anything, it doesn't seem like it helped a lot. 

![immagine](https://github.com/CodingWonders/DISMTools/assets/117264986/4ead596c-6b0c-4647-b3ad-77814b2b408c)
Here is my registry entries, yes it's different from aero.msstyles.

**Comment by CodingWonders** [comment] 2024-04-14 20:34
Then a check for that registry key will be added to the program. By the way, does the program look correctly in light mode? Set it to that theme, close the program, and reopen it

**EDIT:** I also find the visual glitches weird because, like I previously mentioned, I had made consistency improvements just because of Rectify11 that still work with the latest version applied by the installer

**Comment by Fraaaaaunimib** [comment] 2024-04-14 20:40
@winexperiments 

added a mention so you can speak directly from it in case you need anything 

By the way, yes it indeed looks fine, there are just minor glitches due to the theme
![immagine](https://github.com/CodingWonders/DISMTools/assets/117264986/7e0cd54d-7fdd-46b6-a97d-782da46c34be)

**Comment by CodingWonders** [comment] 2024-04-14 21:03
@WinExperiments, how does the program look to you?

**Comment by CodingWonders** [comment] 2024-04-14 21:15
@Fraaaaaunimib, by the way, the other glitches regarding placeholder strings are because of an unsupported language. Force the program to use English in the Personalization settings

**Comment by CodingWonders** [comment] 2024-04-20 18:20
@Fraaaaaunimib, the latest nightly installer features the following warning:

<p align="center">
    <img src="https://github.com/CodingWonders/DISMTools/assets/101426328/b663a1bc-be8f-4292-b8c2-ab377599c647" />
</p>

You'll also need to reconfigure the program, since it now detects unsupported languages and goes back to English, which fixes the placeholder strings

**Comment by Fraaaaaunimib** [comment] 2024-04-21 09:11
Is it normal that the warning msgbox doesn't have a theme manifest?

**Comment by CodingWonders** [comment] 2024-04-21 09:13
> Is it normal that the warning msgbox doesn't have a theme manifest?

This is a representation of the warning using VBScript. Since I haven't set a custom theme, the warning doesn't come up for me

**Comment by CodingWonders** [comment] 2024-05-01 18:14
I'm going to close this issue. Feel free to reopen it or make a new one if you encounter the same problem or a different one

**Closed as completed by CodingWonders** 2024-05-01 18:14 UTC
Labels: bug, good first issue
