### ISSUE TITLE
Error when adding a driver package folder 

### ISSUE THREAD

**Issue by IrishWraith** [CodingWonders/DISMTools#91] opened 2023-12-23 23:54 UTC
**What is the bug about?**
Please describe the bug you're experiencing. Examples:

I had exported drivers from an install.wim file to the directory D:\Drivers
when I went to import them using DISMTools it did not import them all 
if i was doing it command line i would have used the command 
Add-WindowsDriver -Path D:\Mount\ -Driver D:\drivers\ -recurse

I tried again and selected the folder but this time selected no at the prompt to add recursively and when i was presented with a list it listed 7 drivers and then the same driver 90 times. I noticed that this driver was alphabetically the last driver in the folder.
I added this driver alone and then deleted the driver from the folder and tried again and the exact same thing happened with the alphabetically last driver. 

![Screenshot 2023-12-23 165046](https://github.com/CodingWonders/DISMTools/assets/144196452/0026a612-6b77-4366-80ca-dc73b74d405b

**Expected behavior**
all drivers in the folder to be added to the mounted image when selecting recurse and a complete list of drivers when opting to manually add drivers instead of a handful and the last alphabetically driver listed multiple times. 

windows 11 arm64 build 26016.1012

**Comment by CodingWonders** [comment] 2023-12-24 09:08
I don't have an issue with the driver packages in my case and the program returns the exact amount of driver files.

<p align="center">
  <img src="https://github.com/CodingWonders/DISMTools/assets/101426328/4b25489a-2c55-4483-a4b5-abc22c9287f8" />
</p>

Can you perform a directory listing with CMD (`dir D:\drivers\*.inf /s`) and tell me what it returns?

**Comment by CodingWonders** [comment] 2023-12-24 10:11
Never mind, the duplicate items issue has been fixed. It was caused by a function in the background thread responsible for scanning the directory.

<p align="center">
  <img src="https://github.com/CodingWonders/DISMTools/assets/101426328/894f6b6d-6e59-4bd0-907a-58c139b3bd11" />
</p>

Now, can you describe a little bit more the initial issue? I want to determine if it's a program error or a DISM error and also want to fix it if it is the former.

**Comment by CodingWonders** [comment] 2023-12-24 10:33
The driver folder addition issue has been fixed -- DISM was being called without the `/recurse` flag. These fixes will be merged into the stable branch.

Since this issue was reported so soon, I consider the updated versions a recompile of version 0.4. That means I will update the release assets for that version.

You'll need to reinstall this version and, when you do that, settings aren't affected.

**Closed as completed by CodingWonders** 2023-12-24 10:33 UTC
Labels: bug, good first issue

**Comment by IrishWraith** [comment] 2024-01-23 10:10
confirmed now works properly. 

Awesome product. Thank you. especially for ARM64 which is not supported by most others

**Comment by CodingWonders** [comment] 2024-01-23 15:18
You're welcome! ARM64 compatibility is achieved thanks to the program being neutral in architecture
